### ISSUE TITLE
Time and Customize

### ISSUE THREAD

**Issue by HolWag** [jensweimann/awb#1]
Hello Jens,

i use Home Assistant 0.102.3
in automation:
    - platform: time
      at: "18:00:00"
does not work for me.
I changed it to:
    - platform: time_pattern
      hours: '18'
      minutes: '45'
      seconds: '11'
This works. Untestet with '00'.

Where do i have to put the customize informations?
When i put it in customize.yaml, included the file and restart, i got this error:
Component error: customize - Integration 'customize' not found.
i cant use friendly_name: in sensor

Domkloster 4 is a nice example for the address ;-)

Cheers

**Comment by jensweimann** [comment]
Hello HolWag,

I guess you are having some issues with the home assistant config structure. The snippets in the documentation are 100% working examples which I copy pasted from my config. Maybe you want to share more code, so I can have a better look...
