### ISSUE TITLE
Component based off of yours

### ISSUE THREAD

**Issue by tuxuser** [jensweimann/awb#2]
Hi Jens,

Maybe you noticed the fork / derivate of your custom component:

https://github.com/tuxuser/abfallapi_regioit_ha

I gave proper attributions everywhere but just wanted to make sure: Is it okay like this - or did I forget something or something else you might want to have changed?

PS: Thanks for your prior work, it made porting really easy ;)

best regards

**Comment by jensweimann** [comment]
Hi, maybe you can try to add the repo to official HACS...

**Comment by tuxuser** [comment]
PR #3 sent.
