### ISSUE TITLE
Neues Repo

### ISSUE THREAD

**Issue by stibe881** [jensweimann/awb#4]
Hallo Jens
Ist so etwas kompliziert selbst zu machen für jemanden der noch keine grosse Ahnung hat? Ich hätte auch gerne so etwas mit den Daten von unserem Dorf:
https://www.grosswangen.ch/termin-detail/details/kartonsammlung-1578
https://www.grosswangen.ch/termin-detail/details/altpapiersammlung-1579

Was würde ich alles benötigen dafür?

Oder könnte ich einfach Dein Repository anpassen?

Liebe Grüsse

Stibe

**Comment by jensweimann** [comment]
Hallo Stibe,

eine REST-API für die Daten wäre in jedem Fall hilfreich. Eventuell hätte tuxuser Interesse dran, sein Projekt zu erweitern:
https://github.com/tuxuser/abfallapi_regioit_ha

VG
Jens
