### ISSUE TITLE
Only for AWB Cologne or also for other german AWB?

### ISSUE THREAD

**Issue by makeflori** [jensweimann/awb#7]
If I interpret the description correctly, this repo is only for the Cologne AWB or am I wrong? If so, please add that in the title, because german AWB is not only Cologne. Thanks a lot :-)

**Comment by jensweimann** [comment]
Hi, yes it's only for Cologne. I recommend to use https://github.com/mampfes/hacs_waste_collection_schedule instead, since it has much better support and code maintenance. I will archive my resitory
